name: Check Types
on: pull_request
jobs:
  lint:
    name: Check Types
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./apps/chart
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: |
          npm install
      - name: npm install(toast.ui-chart)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: check types
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run check-types
