name: Map Chart Test
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED_PACKAGE_DIRECTORY: ./apps/shared
      WORKING_DIRECTORY: ./apps/map-chart
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: |
          npm install
      - name: set shared package bundle for workspace
        working-directory: ${{ env.SHARED_PACKAGE_DIRECTORY }}
        run: |
          npm install
          npm run build
      - name: npm install(toast ui map chart)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run test
